import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, ArrowDown, Sparkles, Code2, Check, Zap, Menu, X, Braces, Terminal, Gamepad2, GraduationCap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import labImage from '@/assets/js-lab.jpg';
import { types, type TypeInfo } from '@/lib/data-types';
import { Playground } from '@/components/explorer/playground';
import { Detective, GuessGame, MemoryGame, Quiz, ReferenceDemo, SectionHeading } from '@/components/explorer/activities';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export const Route=createFileRoute('/')({head:()=>({meta:[{title:'JavaScript Data Types Explorer — Play. Experiment. Learn.'},{name:'description',content:'An interactive JavaScript learning lab for beginner CSE students. Explore data types, experiment with live code, and test your knowledge with games.'},{property:'og:title',content:'JavaScript Data Types Explorer'},{property:'og:description',content:'Don’t just learn data types. Play with them! A browser-only coding lab for beginner CSE students.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Index});
const nav=[['Home','home'],['Data Types','data-types'],['Playground','playground'],['typeof Detective','detective'],['Primitive vs Reference','comparison'],['Games','games'],['Quiz','quiz']];
function Index(){const [menu,setMenu]=useState(false);const [filter,setFilter]=useState('All types');const [selected,setSelected]=useState<TypeInfo|null>(null);const [expression,setExpression]=useState<string|null>(null);const [heroValue,setHeroValue]=useState('"Hello JavaScript"');const [resetKey,setResetKey]=useState(0);
 const explore=(type:TypeInfo)=>{setExpression(type.expression);setSelected(null);document.getElementById('playground')?.scrollIntoView({behavior:'smooth'});};
 return <div id="home"><header className="lab-nav sticky top-0 z-40"><div className="container-lab h-full grid grid-cols-[minmax(0,1fr)_auto] lg:flex items-center gap-5"><a href="#home" className="flex items-center min-w-0 gap-2.5 shrink-0"><span className="bg-primary text-primary-foreground rounded h-8 w-8 grid place-items-center font-bold text-base">JS</span><span className="text-sm font-semibold truncate">Data Types <span className="brand-full">Explorer</span><span className="text-primary">.</span></span></a><nav className="desktop-links flex items-center justify-center gap-5 grow" aria-label="Main navigation">{nav.map(([name,id])=><a key={id} href={`#${id}`} className="text-[11px] text-muted-foreground hover:text-primary transition-colors whitespace-nowrap">{name}</a>)}</nav><div className="flex items-center gap-2 shrink-0"><Button size="sm" className="hidden sm:inline-flex" asChild><a href="#data-types">Start Learning <ArrowRight/></a></Button><Button variant="ghost" size="icon" className="lg:hidden" aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="lg:hidden bg-background border-b border-border px-5 py-3 grid gap-1" aria-label="Mobile navigation">{nav.map(([name,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)} className="text-sm text-muted-foreground py-2">{name}</a>)}</nav>}</header>
 <main><section className="hero"><img src={labImage} className="hero-art" width={1536} height={1024} alt="Floating yellow JavaScript cube with glass code symbols"/><div className="container-lab"><div className="hero-content"><div className="eyebrow"><span className="w-1.5 h-1.5 bg-primary rounded-full"/> YOUR FIRST JAVASCRIPT ADVENTURE</div><h1>JavaScript<br/>Data Types <span className="text-primary">Explorer</span><span className="text-primary">.</span></h1><p className="text-xl text-foreground mb-3">Don’t just learn data types. <span className="text-primary">Play with them!</span></p><p className="text-sm text-muted-foreground leading-6 max-w-md">A little curiosity. A little code. A whole new way to understand the values that power JavaScript.</p><div className="flex flex-wrap gap-3 mt-7"><Button size="lg" asChild><a href="#data-types">Start Exploring <ArrowRight/></a></Button><Button variant="outline" size="lg" asChild><a href="#playground"><Code2/> Try the Playground</a></Button></div><div className="hero-code mt-8"><div className="code-head"><span className="dot"/><span className="dot"/><span className="dot"/><span className="ml-3 font-mono">hello-world.js</span><span className="ml-auto">● LIVE</span></div><div className="p-5 font-mono text-[13px] leading-7"><div><span className="text-primary">let</span> value = <select aria-label="Hero example value" value={heroValue} onChange={e=>setHeroValue(e.target.value)} className="text-code bg-transparent border-0 max-w-full"><option value={'"Hello JavaScript"'}>"Hello JavaScript"</option><option value="42">42</option><option value="true">true</option></select>;</div><div>console.<span className="text-primary">log</span>(<span className="text-primary">typeof</span> value);</div><div className="mt-3 pt-3 border-t border-border flex justify-between items-center"><span className="text-code">→ {heroValue==='42'?'number':heroValue==='true'?'boolean':'string'}</span><span className="text-[10px] text-muted-foreground">OUTPUT <Check size={11} className="inline ml-1 text-success"/></span></div></div></div><div className="flex flex-wrap gap-5 text-[11px] text-muted-foreground mt-5"><span className="flex items-center gap-1.5"><Braces size={13}/> 10 data types</span><span className="flex items-center gap-1.5"><Zap size={13}/> Live experiments</span><span className="flex items-center gap-1.5"><Gamepad2 size={13}/> Learn by playing</span></div></div></div></section>
 <section id="data-types" className="section-lab"><div className="container-lab"><SectionHeading number="01" title="Explore the Data Type Universe" description="Every value has a type. Meet the building blocks of JavaScript."><div className="flex gap-1 p-1 rounded-md bg-secondary" role="group" aria-label="Filter data types">{['All types','Primitive','Reference'].map(f=><Button key={f} variant={filter===f?'default':'ghost'} size="sm" onClick={()=>setFilter(f)} aria-pressed={filter===f}>{f}</Button>)}</div></SectionHeading><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{types.filter(t=>filter==='All types'||t.group===filter).map(t=><article key={t.name} className={`type-card type-${t.name.toLowerCase()}`}><div className="flex items-center justify-between"><span className="type-icon">{t.icon}</span><span className="text-[9px] text-muted-foreground uppercase">{t.group}</span></div><h3 className="text-lg font-semibold mt-4">{t.name}</h3><p className="text-xs text-muted-foreground mt-1">{t.description}</p><pre className="type-example">{t.example}</pre><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground font-mono">typeof → <span className="text-foreground">{t.result}</span></span><Button size="sm" variant="ghost" className="text-xs px-0 h-7" onClick={()=>setSelected(t)}>Explore <ArrowRight/></Button></div></article>)}</div><div className="remember mt-5 flex items-start gap-3"><Sparkles size={17} className="text-primary shrink-0 mt-0.5"/><p><strong className="text-primary">Remember:</strong> Arrays and functions are technically objects. We explore them separately because each has its own superpowers. And yes — <code className="font-mono">typeof null</code> returns <code className="font-mono">"object"</code>. That’s a historical JavaScript quirk, not a mistake you made.</p></div></div></section>
 <section id="playground" className="section-lab"><div className="container-lab"><SectionHeading number="02" title="Type It. Run It. See It." description="What happens if you change the value? Let's find out."><span className="text-xs text-success flex items-center gap-2"><span className="h-1.5 w-1.5 bg-success rounded-full"/> Your browser is the lab</span></SectionHeading><Playground expression={expression} onExpressionUsed={()=>setExpression(null)}/></div></section>
 <section id="detective" className="section-lab"><div className="container-lab"><SectionHeading number="03" title="Become a typeof Detective 🕵️" description="Look at the clues. Make a prediction. Reveal the truth."/><div className="grid md:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)] gap-8 items-center"><Detective/><div className="px-3"><div className="type-icon mb-5"><Terminal size={21}/></div><h3 className="text-2xl font-semibold">One question.<br/>A powerful little operator.</h3><p className="text-muted-foreground text-sm leading-7 mt-4"><code className="text-primary font-mono">typeof</code> asks JavaScript: “What kind of value is this?” Its answer is always a string, like <code className="text-code">"number"</code> or <code className="text-code">"boolean"</code>.</p><div className="remember mt-6"><strong className="text-primary">Look twice!</strong><p className="mt-2">Quotes matter. <code>25</code> is a number. <code>"25"</code> is a string.</p></div></div></div></div></section>
 <section id="comparison" className="section-lab"><div className="container-lab"><SectionHeading number="04" title="Primitive vs Reference" description="Copy a value, or share a link? See the difference in action."/><ReferenceDemo/></div></section>
 <section id="games" className="section-lab"><div className="container-lab"><SectionHeading number="05" title="Less memorizing. More playing." description="Put your new instincts to the test."><span className="text-xs text-primary flex items-center gap-2"><Gamepad2 size={16}/> THE GAME ZONE</span></SectionHeading><div className="grid md:grid-cols-2 gap-5"><GuessGame resetKey={resetKey}/><MemoryGame key={resetKey}/></div></div></section>
 <section className="section-lab"><div className="container-lab"><SectionHeading number="06" title="Your data type cheat sheet" description="A quick side-by-side look at everything you've explored."/><div className="border border-border rounded-lg overflow-x-auto"><table className="compare-table"><thead><tr><th>DATA TYPE</th><th>EXAMPLE</th><th>TYPEOF RESULT</th></tr></thead><tbody>{types.map(t=><tr key={t.name}><td className="font-medium">{t.name}</td><td><code>{t.name==='Number'?'25':t.name==='BigInt'?'123n':t.name==='Undefined'?'undefined':t.name==='Object'?'{}':t.name==='Array'?'[]':t.name==='Function'?'function(){}':t.example}</code></td><td><code className="text-primary">{t.result}</code>{t.name==='Null'&&<span className="ml-2 text-xs text-muted-foreground">← surprise!</span>}</td></tr>)}</tbody></table></div></div></section>
 <section id="quiz" className="section-lab"><div className="container-lab"><SectionHeading number="07" title="The Quick Challenge" description="Five questions. No pressure. How much have you discovered?"><span className="text-xs flex items-center gap-2 text-primary"><GraduationCap size={17}/> READY WHEN YOU ARE</span></SectionHeading><Quiz resetKey={resetKey}/></div></section>
 <section className="section-lab"><div className="container-lab"><SectionHeading number="08" title="JavaScript Surprises 🤯" description="Even JavaScript has a few plot twists. Here's your heads-up."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{code:'typeof null',result:'object',text:'A historical quirk. Null is still a primitive value.'},{code:'typeof []',result:'object',text:'Arrays are special objects. Array.isArray([]) returns true.'},{code:'typeof function(){}',result:'function',text:'Functions are callable objects with their own typeof result.'},{code:'typeof NaN',result:'number',text:'“Not a Number” is a special value within the Number type.'}].map((s,i)=><article className="type-card" key={s.code}><div className="eyebrow">PLOT TWIST 0{i+1}</div><pre className="font-mono text-xs mt-5 break-all whitespace-pre-wrap">{s.code}</pre><p className="font-mono text-primary mt-2">→ "{s.result}"</p><p className="text-xs text-muted-foreground leading-6 mt-4">{s.text}</p></article>)}</div></div></section>
 <section className="final-band"><span className="inline-grid place-items-center h-10 w-10 bg-primary text-primary-foreground font-bold rounded-md mb-5">JS</span><h2 className="text-3xl sm:text-4xl font-semibold">Ready to Master JavaScript?</h2><p className="text-muted-foreground text-sm mt-4">Explore <span className="text-primary mx-2">→</span> Experiment <span className="text-primary mx-2">→</span> Predict <span className="text-primary mx-2">→</span> Learn</p><div className="flex flex-wrap justify-center gap-3 mt-7"><Button size="lg" onClick={()=>{setResetKey(k=>k+1);document.getElementById('games')?.scrollIntoView({behavior:'smooth'});}}><Gamepad2/> Play Again</Button><Button variant="outline" size="lg" asChild><a href="#data-types">Explore Data Types <ArrowRight/></a></Button></div></section></main>
 <footer className="border-t border-border"><div className="container-lab py-6 flex flex-wrap gap-3 justify-between text-[11px] text-muted-foreground"><span>JavaScript Data Types Explorer <span className="mx-2">|</span> Built for CSE Students</span><span>Made for curious minds. No installation needed.</span></div></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="max-w-lg">{selected&&<><div className={`type-icon type-${selected.name.toLowerCase()}`}>{selected.icon}</div><DialogTitle className="text-2xl">Meet {selected.name}</DialogTitle><DialogDescription className="text-sm leading-7">{selected.detail}</DialogDescription><pre className="bg-background p-5 rounded-md text-code font-mono whitespace-pre-wrap break-all text-sm">{selected.example}<br/><span className="text-primary">typeof → "{selected.result}"</span></pre>{selected.name==='Array'&&<p className="font-mono text-sm text-success">Array.isArray([10, 20, 30]) → true</p>}<Button onClick={()=>explore(selected)}>Experiment with {selected.name}<ArrowRight/></Button></>}</DialogContent></Dialog>
 </div>;
}
