import { createFileRoute } from '@tanstack/react-router';
import { useCallback, useState } from 'react';
import { ArrowRight, Check, Sparkles, Code2, Menu, X, Braces, Gamepad2, GraduationCap, Variable, Calculator, WandSparkles, Layers, Timer, ShieldAlert, Terminal, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import labImage from '@/assets/js-lab.jpg';
import { types, type TypeInfo } from '@/lib/data-types';
import { commonUses, operatorGroups, predictionQuestions, hoistingQuestions, operatorQuestions, detectiveQuestions, finalQuestions } from '@/lib/fundamentals';
import { Playground } from '@/components/explorer/playground';
import { ReferenceDemo, SectionHeading, MemoryGame } from '@/components/explorer/activities';
import { VariablesLab, OperatorsLab, CoercionLab, HoistingLab, QuestionGame, Code, Modes } from '@/components/explorer/fundamentals-activities';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'JavaScript Fundamentals Explorer — Learn by Experimenting'},{name:'description',content:'An interactive browser coding laboratory for beginner CSE students. Explore variables, data types, operators, coercion, hoisting and TDZ, then play challenges and a 20-question quiz.'},{property:'og:title',content:'JavaScript Fundamentals Explorer'},{property:'og:description',content:'Learn JavaScript by seeing it, changing it, and breaking it! Interactive experiments, safe code execution and learning games.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Index});
const topics=[
 {name:'Variables',id:'variables',description:'Meet var, let and const.',icon:Variable},
 {name:'Data Types',id:'data-types',description:'Discover what values are made of.',icon:Braces},
 {name:'Reference Types',id:'reference-types',description:'Copy values. Share objects.',icon:Layers},
 {name:'Operators',id:'operators',description:'Calculate, compare, and decide.',icon:Calculator},
 {name:'Type Coercion',id:'coercion',description:'Watch values change their type.',icon:WandSparkles},
 {name:'Hoisting',id:'hoisting',description:'Before the first line runs.',icon:Timer},
 {name:'TDZ',id:'tdz',description:'Step into the danger zone.',icon:ShieldAlert},
 {name:'Interactive Playground',id:'playground',description:'Your code. Your experiments.',icon:Terminal},
 {name:'JavaScript Challenges',id:'challenges',description:'Predict it. Prove it.',icon:Gamepad2},
 {name:'Final Quiz',id:'quiz',description:'20 questions. Find your level.',icon:GraduationCap},
];
const nav=[['Home','home'],...topics.map(t=>[t.name==='Type Coercion'?'Coercion':t.name==='Interactive Playground'?'Playground':t.name==='JavaScript Challenges'?'Challenges':t.name==='Final Quiz'?'Quiz':t.name,t.id])];
function LabSection({id,number,title,description,children}:{id:string;number:string;title:string;description:string;children:React.ReactNode}) {return <section id={id} className="section-lab"><div className="container-lab"><SectionHeading number={number} title={title} description={description}/>{children}</div></section>;}
function Index(){
 const [menu,setMenu]=useState(false);const [filter,setFilter]=useState('All types');const [selected,setSelected]=useState<TypeInfo|null>(null);const [expression,setExpression]=useState<string|null>(null);const [heroValue,setHeroValue]=useState('"Hello JavaScript"');const [progress,setProgress]=useState<Record<string,number>>({});const [typeAnswer,setTypeAnswer]=useState('');const [challengeMode,setChallengeMode]=useState('Predict the Output');const [reference,setReference]=useState('Object');
 const clearExpression=useCallback(()=>setExpression(null),[]);
 const complete=(id:string)=>setProgress(p=>({...p,[id]:100}));const started=(id:string)=>setProgress(p=>({...p,[id]:Math.max(p[id]??0,25)}));
 const explore=(t:TypeInfo)=>{setExpression(t.expression);setSelected(null);document.getElementById('playground')?.scrollIntoView({behavior:'smooth'});};
 const questions=challengeMode==='Predict the Output'?predictionQuestions:challengeMode==='Variables + Hoisting + TDZ'?hoistingQuestions:operatorQuestions;
 const referenceExamples:Record<string,string>={Object:'let person = {\n  name: "John", age: 20\n};\ntypeof person // "object"',Array:'let numbers = [10, 20, 30];\ntypeof numbers // "object"',Function:'function greet() {\n  return "Hello";\n}\ntypeof greet // "function"'};
 const finished=topics.filter(t=>progress[t.id]===100).length;
 return <div id="home"><header className="lab-nav sticky top-0 z-40"><div className="container-lab h-full flex items-center gap-4"><a href="#home" className="flex items-center gap-2.5 min-w-0 shrink-0"><span className="bg-primary text-primary-foreground rounded h-8 w-8 grid place-items-center font-bold">JS</span><span className="text-sm font-semibold">Fundamentals <span className="brand-full">Explorer</span></span></a><nav className="desktop-links flex items-center justify-center gap-3 grow" aria-label="Main navigation">{nav.map(([name,id])=><a key={id} href={`#${id}`} className="text-[10px] text-muted-foreground hover:text-primary whitespace-nowrap">{name}</a>)}</nav><div className="ml-auto flex items-center gap-2"><Button size="sm" className="hidden sm:inline-flex" asChild><a href="#topics">Start Learning<ArrowRight/></a></Button><Button size="icon" variant="ghost" className="nav-toggle" aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="mobile-links bg-background border-b border-border px-5 py-3 grid grid-cols-2 gap-2" aria-label="Mobile navigation">{nav.map(([name,id])=><a key={id} href={`#${id}`} className="text-sm py-2" onClick={()=>setMenu(false)}>{name}</a>)}</nav>}</header>
 <main><section className="hero"><img src={labImage} className="hero-art" width={1536} height={1024} alt="Floating JavaScript cube and glowing glass code symbols"/><div className="container-lab"><div className="hero-content"><div className="eyebrow"><span className="w-1.5 h-1.5 bg-primary rounded-full"/> YOUR JAVASCRIPT ADVENTURE STARTS HERE</div><h1>JavaScript<br/>Fundamentals<br/><span className="text-primary">Explorer.</span></h1><p className="text-lg text-foreground max-w-md">Learn JavaScript by seeing it, changing it, and breaking it!</p><div className="flex flex-wrap gap-3 mt-6"><Button size="lg" asChild><a href="#topics">Start Learning<ArrowRight/></a></Button><Button variant="outline" size="lg" asChild><a href="#playground"><Code2/>Open Playground</a></Button></div><div className="hero-code mt-6"><div className="code-head"><span className="dot"/><span className="dot"/><span className="dot"/><span className="ml-3 font-mono">first-experiment.js</span><span className="ml-auto text-success">LIVE</span></div><div className="p-5 font-mono text-xs leading-7"><div><span className="text-primary">let</span> value = <select aria-label="Hero example value" value={heroValue} onChange={e=>setHeroValue(e.target.value)} className="text-code bg-background border border-border rounded min-w-0 max-w-full"><option value={'"Hello JavaScript"'}>"Hello JavaScript"</option><option value="42">42</option><option value="true">true</option></select>;</div><div>console.<span className="text-primary">log</span>(<span className="text-primary">typeof</span> value);</div><div aria-live="polite" className="mt-3 pt-3 border-t border-border flex justify-between"><span className="text-code">→ {heroValue==='42'?'number':heroValue==='true'?'boolean':'string'}</span><span className="text-muted-foreground">OUTPUT <Check className="inline text-success" size={12}/></span></div></div></div><div className="flex flex-wrap gap-4 text-xs text-muted-foreground mt-5"><span>10 topics</span><span>Live experiments</span><span>20-question finale</span></div></div></div></section>
 <section id="topics" className="section-lab"><div className="container-lab"><SectionHeading number="00" title="Choose your next discovery" description="Learn → Experiment → Predict → Run → Get Feedback → Understand"><span className="achievement"><Trophy size={15}/>{finished===10?'Lab complete':`${finished} / 10 topics completed`}</span></SectionHeading><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4">{topics.map((t,i)=><article key={t.id} className="type-card topic-card"><div className="flex justify-between"><t.icon className="text-primary" size={22}/><span className="text-xs text-muted-foreground">{String(i+1).padStart(2,'0')}</span></div><h3 className="font-semibold mt-5">{t.name}</h3><p className="text-xs text-muted-foreground mt-2 min-h-8">{t.description}</p><div className="progress-track mt-5"><progress aria-label={`${t.name} topic progress`} value={progress[t.id]??0} max={100}/></div><div className="flex justify-between items-center mt-3"><span className="text-xs text-muted-foreground">{progress[t.id]??0}%</span><Button variant="ghost" size="sm" className="px-0" asChild><a href={`#${t.id}`} onClick={()=>started(t.id)}>Explore<ArrowRight/></a></Button></div></article>)}</div></div></section>
 <LabSection id="variables" number="01" title="Meet var, let and const" description="Three ways to name a value. Different rules for changing and sharing it."><VariablesLab onComplete={()=>complete('variables')}/></LabSection>
 <section id="data-types" className="section-lab"><div className="container-lab"><SectionHeading number="02" title="Explore JavaScript Data Types" description="Click a value, discover its type, and try a mini challenge."><Modes values={['All types','Primitive','Reference']} value={filter} onChange={setFilter} label="Filter data types"/></SectionHeading><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{types.filter(t=>filter==='All types'||t.group===filter).map(t=><article key={t.name} className={`type-card type-${t.name.toLowerCase()}`}><div className="flex justify-between items-center"><span className="type-icon">{t.icon}</span><span className="text-[10px] text-muted-foreground">{t.group}</span></div><h3 className="text-lg font-semibold mt-4">{t.name}</h3><p className="text-xs text-muted-foreground mt-1">{t.description}</p><pre className="type-example">{t.example}</pre><div className="flex justify-between items-center"><span className="text-xs font-mono text-muted-foreground">typeof → {t.result}</span><Button variant="ghost" size="sm" className="px-0" onClick={()=>{setSelected(t);setTypeAnswer('');started('data-types');}}>Explore<ArrowRight/></Button></div></article>)}</div></div></section>
 <LabSection id="reference-types" number="03" title="Reference Types" description="Objects, arrays and functions hold more than simple values."><div className="mb-6"><Modes values={['Object','Array','Function']} value={reference} label="Reference example" onChange={r=>{setReference(r);complete('reference-types');}}/><Code>{referenceExamples[reference]}</Code><p className="text-sm text-muted-foreground">Arrays and functions are technically objects. We commonly learn them separately as reference types. Functions are objects you can call.</p></div><SectionHeading number="↳" title="Value vs Reference" description="Change a copy. Then change a shared object."/><div onClick={()=>complete('reference-types')}><ReferenceDemo/></div></LabSection>
 <LabSection id="operators" number="04" title="JavaScript Operators Lab" description="Choose an operator. Predict a result. Put it to the test."><OperatorsLab onComplete={()=>complete('operators')}/></LabSection>
 <LabSection id="coercion" number="05" title="Type Coercion Magic" description="Type coercion is when JavaScript converts one data type into another during an operation."><CoercionLab onComplete={()=>complete('coercion')}/></LabSection>
 <LabSection id="hoisting" number="06" title="Hoisting — Before Your Code Runs" description="JavaScript processes declarations before executing the code."><HoistingLab onComplete={()=>complete('hoisting')}/></LabSection>
 <LabSection id="tdz" number="07" title="TDZ — The Danger Zone" description="From scope entry to initialization, let and const cannot be accessed."><HoistingLab tdz onComplete={()=>complete('tdz')}/></LabSection>
 <LabSection id="playground" number="08" title="Your Interactive JavaScript Playground" description="See it. Change it. Predict it. Run it."><Playground expression={expression} onExpressionUsed={clearExpression} onComplete={()=>complete('playground')}/></LabSection>
 <LabSection id="detective" number="↳" title="Become a typeof Detective 🕵️" description="Nine clues. One little operator. What's your prediction?"><QuestionGame title="typeof Detective" questions={detectiveQuestions} onComplete={()=>complete('challenges')}/></LabSection>
 <LabSection id="surprises" number="↳" title="JavaScript WTF? 🤯" description="Surprising at first. Understandable after an experiment."><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[{code:'typeof null',result:'"object"',why:'A historical quirk. Null is still primitive.'},{code:'typeof []',result:'"object"',why:'Arrays are special objects.'},{code:'typeof NaN',result:'"number"',why:'NaN is a special value in the Number type.'},{code:'"5" + 2',result:'"52"',why:'The number becomes text. + joins the strings.'},{code:'"5" - 2',result:'3',why:'Subtraction converts the text to a number.'},{code:'true + true',result:'2',why:'Each true becomes the number 1.'}].map(s=><Surprise key={s.code} {...s}/>)}</div></LabSection>
 <LabSection id="challenges" number="09" title="Predict. Run. Level up." description="A little code. A prediction. A new discovery."><div className="mb-5"><Modes values={['Predict the Output','Variables + Hoisting + TDZ','Operator Challenge']} value={challengeMode} onChange={setChallengeMode} label="Challenge mode"/></div><QuestionGame key={challengeMode} title={challengeMode} questions={questions} onComplete={()=>complete('challenges')}/><div className="mt-6"><MemoryGame/></div></LabSection>
 <LabSection id="quiz" number="10" title="The Final Quiz" description="20 questions across the lab. What is your JavaScript level?"><QuestionGame title="JavaScript Fundamentals Quiz" questions={finalQuestions} final onComplete={()=>complete('quiz')}/></LabSection>
 <LabSection id="cheat-sheet" number="↳" title="Your interactive cheat sheet" description="A quick reminder of the discoveries you've made."><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-7">{[{name:'Variables',id:'variables',items:['var → function scoped','let → block scoped','const → block scoped']},{name:'Primitive Types',id:'data-types',items:types.filter(t=>t.group==='Primitive').map(t=>t.name)},{name:'Common Reference Types',id:'reference-types',items:['Object','Array','Function']},{name:'Operators',id:'operators',items:Object.keys(operatorGroups)},{name:'Important Concepts',id:'hoisting',items:['Hoisting','TDZ','Type Coercion','typeof','Scope']}].map(g=><div key={g.name}><h3 className="text-primary font-semibold mb-3">{g.name}</h3><div className="flex flex-wrap gap-1">{g.items.map(i=><Button size="sm" variant="ghost" key={i} asChild><a href={`#${i==='TDZ'?'tdz':i==='Type Coercion'?'coercion':i==='typeof'?'detective':i==='Scope'?'variables':g.id}`}>{i}<ArrowRight/></a></Button>)}</div></div>)}</div></LabSection>
 <section className="final-band"><Sparkles className="text-primary mx-auto mb-4"/><h2 className="text-3xl font-semibold">Keep your curiosity running.</h2><div className="flex flex-wrap justify-center gap-3 mt-6"><Button size="lg" asChild><a href="#playground"><Code2/>Open Playground</a></Button><Button variant="outline" size="lg" asChild><a href="#topics">Next discovery<ArrowRight/></a></Button></div></section></main>
 <footer className="border-t border-border"><div className="container-lab py-6 flex flex-wrap justify-between gap-3 text-xs text-muted-foreground"><span>JavaScript Fundamentals Explorer | Built for CSE Students</span><span>No installation. Just curiosity.</span></div></footer>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null);}}><DialogContent className="max-w-lg">{selected&&<><DialogTitle className="text-2xl">Meet {selected.name}</DialogTitle><DialogDescription className="leading-6">{selected.detail}</DialogDescription><Code>{selected.example}</Code><p className="text-xs text-muted-foreground"><strong className="text-primary">Common use:</strong> {commonUses[selected.name]}</p><p className="text-sm">Mini challenge: what does typeof return?</p><Modes values={Array.from(new Set([selected.result,'string','number','object','function','undefined','boolean','bigint','symbol']))} value={typeAnswer} label="Data type mini challenge" onChange={a=>{setTypeAnswer(a);if(a===selected.result)complete('data-types');}}/>{typeAnswer&&<p role="status" className={`feedback ${typeAnswer===selected.result?'':'wrong'}`}>{typeAnswer===selected.result?'Correct!':`Not quite. typeof returns "${selected.result}".`}</p>}<Button onClick={()=>explore(selected)}>Experiment with {selected.name}<ArrowRight/></Button></>}</DialogContent></Dialog>
 </div>;
}
function Surprise({code,result,why}:{code:string;result:string;why:string}) {const [open,setOpen]=useState(false);return <article className="type-card"><pre className="font-mono text-sm">{code}</pre><Button variant="ghost" size="sm" className="px-0 mt-4" onClick={()=>setOpen(v=>!v)}>{open?'Hide result':'Reveal surprise'}<Sparkles/></Button>{open&&<div role="status"><p className="font-mono text-primary mt-2">→ {result}</p><p className="text-xs text-muted-foreground mt-3 leading-6">{why}</p></div>}</article>;}
