import { useState } from 'react';
import { ArrowRight, Check, RotateCcw, Eye, Trophy, Link2, Copy, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { types, challenge, scoreMessage } from '@/lib/data-types';

export function SectionHeading({number,title,description,children}:{number:string;title:string;description:string;children?:React.ReactNode}) {return <div className="section-heading"><div className="min-w-0"><div className="eyebrow"><span className="text-muted-foreground">{number} /</span> THE LEARNING LAB</div><h2>{title}</h2><p className="section-description">{description}</p></div>{children}</div>;}

export function GuessGame({resetKey}:{resetKey:number}) {return <GuessRound key={resetKey}/>;}
function GuessRound(){
 const [order,setOrder]=useState([1,0,3,7,9]);const [step,setStep]=useState(0);const [score,setScore]=useState(0);const [answer,setAnswer]=useState<string|null>(null);
 const typeIndex=order[step];const item=typeIndex===undefined?undefined:types[typeIndex];const done=step>=5;
 const reset=()=>{setOrder([...types.keys()].sort(()=>Math.random()-.5).slice(0,5));setStep(0);setScore(0);setAnswer(null);};
 return <div className="activity"><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">What Am I?</h3><span className="text-xs text-primary">Score: {score} / 5</span></div><p className="text-sm text-muted-foreground mt-2">One value. One type. What's your guess?</p><div className="progress-track mt-5"><progress aria-label="Guessing game progress" value={done?5:step} max={5}/></div>{done?<div className="py-8 text-center"><Trophy className="mx-auto text-primary" size={40}/><h4 className="text-xl mt-4">{scoreMessage(score,5)}</h4><p className="text-muted-foreground my-3">You got {score} out of 5 correct.</p><Button onClick={reset}><RotateCcw/> Play again</Button></div>:item&&<><div className="mystery">{item.example}</div><p className="text-sm mb-4">What data type is this?</p><div className="grid grid-cols-2 gap-2">{Array.from(new Set([item.name,...['String','Number','Boolean','Object'].filter(v=>v!==item.name)])).slice(0,4).sort().map(option=><Button variant="outline" key={option} disabled={answer!==null} onClick={()=>{setAnswer(option);if(option===item.name)setScore(s=>s+1);}}>{option}</Button>)}</div>{answer&&<><div role="status" className={`feedback ${answer===item.name?'':'wrong'}`}><strong>{answer===item.name?'✓ You got it!':`Not quite — it's ${item.name}.`}</strong><p className="mt-1">{item.detail}</p></div><Button variant="ghost" className="mt-3" onClick={()=>{setStep(s=>s+1);setAnswer(null);}}>{step===4?'See score':'Next value'}<ArrowRight/></Button></>}<p className="text-xs text-muted-foreground mt-4">Question {step+1} of 5</p></>}</div>;
}

const detectiveCases=[{expression:'typeof "Hello"',answer:'string',why:'Text in quotes is a string.'},{expression:'typeof 25',answer:'number',why:'Whole numbers and decimals both have type number.'},{expression:'typeof true',answer:'boolean',why:'true and false are booleans.'},{expression:'typeof undefined',answer:'undefined',why:'No value has been assigned yet.'},{expression:'typeof null',answer:'object',why:'A historical JavaScript quirk! Null is a primitive, even though typeof says object.'},{expression:'typeof [1, 2, 3]',answer:'object',why:'Arrays are special objects. Use Array.isArray to detect them.'},{expression:'typeof {name: "John"}',answer:'object',why:'Curly braces group related values into an object.'}];
export function Detective(){const [index,setIndex]=useState(0);const [prediction,setPrediction]=useState('');const [revealed,setRevealed]=useState(false);const item=detectiveCases[index];if(!item)return null;return <div className="activity"><div className="flex justify-between items-center gap-3"><span className="eyebrow"><Eye size={15}/> CASE FILE {String(index+1).padStart(2,'0')}</span><span className="text-xs text-muted-foreground">{index+1} / {detectiveCases.length}</span></div><div className="mystery">{item.expression}</div><label className="text-sm block mb-2" htmlFor="prediction">Your prediction</label><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><select id="prediction" className="bg-background border border-border rounded-md px-3 py-2 text-sm min-w-0" value={prediction} disabled={revealed} onChange={e=>setPrediction(e.target.value)}><option value="">Choose a result...</option>{['string','number','boolean','undefined','object','function','bigint','symbol'].map(t=><option key={t}>{t}</option>)}</select><Button onClick={()=>setRevealed(true)} disabled={!prediction||revealed}><Eye/> Reveal Answer</Button></div>{revealed&&<div role="status" className={`feedback ${prediction===item.answer?'':'wrong'}`}><strong>{prediction===item.answer?'Case solved!':'A useful discovery!'} → "{item.answer}"</strong><p className="mt-1">{item.why}</p></div>}<div className="flex justify-between mt-5"><Button variant="ghost" disabled={index===0} onClick={()=>{setIndex(i=>i-1);setPrediction('');setRevealed(false);}}>Previous</Button><Button variant="ghost" onClick={()=>{setIndex(i=>(i+1)%detectiveCases.length);setPrediction('');setRevealed(false);}}>Next case <ArrowRight/></Button></div></div>;}

export function ReferenceDemo(){const [primitive,setPrimitive]=useState(false);const [reference,setReference]=useState(false);return <div className="grid md:grid-cols-2 gap-5"><div className="activity"><div className="eyebrow"><Copy size={16}/> PRIMITIVE</div><h3 className="text-xl font-semibold mt-3">A copy of the value.</h3><p className="text-muted-foreground text-sm mt-2">Simple values like text, numbers, and booleans. Each variable keeps its own value.</p><div className="flex flex-wrap gap-2 my-5">{types.filter(t=>t.group==='Primitive').map(t=><span key={t.name} className="text-xs bg-secondary px-2 py-1 rounded">{t.name}</span>)}</div><pre className="bg-background rounded-md p-4 text-xs font-mono leading-7 overflow-x-auto">{'let a = 10;\nlet b = a;\n'}<span className="text-primary">{primitive?'b = 20;':'// change b next'}</span></pre><div className="grid grid-cols-2 gap-4 my-5">{['a','b'].map(name=><div key={name} className="border border-border rounded-md p-4 text-center font-mono"><span className="text-muted-foreground text-sm">{name} → </span><span className="text-2xl text-code">{name==='b'&&primitive?20:10}</span></div>)}</div><Button variant="outline" onClick={()=>setPrimitive(v=>!v)}><RotateCcw/>{primitive?'Reset values':'Set b = 20'}</Button>{primitive&&<p role="status" className="feedback">b changes. a stays 10. They are independent copies.</p>}</div><div className="activity"><div className="eyebrow"><Link2 size={16}/> REFERENCE / NON-PRIMITIVE</div><h3 className="text-xl font-semibold mt-3">A link to the same object.</h3><p className="text-muted-foreground text-sm mt-2">Objects group values together. Copying a variable copies its link, not the object.</p><div className="flex flex-wrap gap-2 my-5">{['Object','Array','Function'].map(t=><span key={t} className="text-xs bg-secondary px-2 py-1 rounded">{t}</span>)}</div><pre className="bg-background rounded-md p-4 text-xs font-mono leading-7 overflow-x-auto">{'let person1 = { name: "John" };\nlet person2 = person1;\n'}<span className="text-primary">{reference?'person2.name = "Alex";':'// change person2 next'}</span></pre><div className="grid grid-cols-[auto_minmax(0,1fr)] gap-4 my-5 items-center"><div className="font-mono text-xs leading-9">person1 →<br/>person2 →</div><div className="border border-primary/40 rounded-md p-4 font-mono text-code text-sm">{'{ name: "'}{reference?'Alex':'John'}{'" }'}<div className="text-muted-foreground font-sans text-xs mt-2">One shared object</div></div></div><Button variant="outline" onClick={()=>setReference(v=>!v)}><RotateCcw/>{reference?'Reset object':'Set person2.name = "Alex"'}</Button>{reference&&<p role="status" className="feedback">Both now show Alex — they point to the same object.</p>}</div></div>;}

const memoryPairs=[{value:'"Hello"',name:'String'},{value:'25',name:'Number'},{value:'true',name:'Boolean'},{value:'null',name:'Null'},{value:'undefined',name:'Undefined'},{value:'[1,2,3]',name:'Array'},{value:'{name:"John"}',name:'Object'}];
export function MemoryGame(){const [selected,setSelected]=useState<string|null>(null);const [matched,setMatched]=useState<string[]>([]);const [feedback,setFeedback]=useState('');const match=(name:string)=>{if(!selected)return;if(selected===name){setMatched(m=>[...m,name]);setFeedback('Perfect match!');setSelected(null);}else setFeedback('Not a match yet. Try another type.');};return <div className="activity"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 items-center"><h3 className="text-xl font-semibold">Make the connection</h3><span className="text-sm text-primary">{matched.length} / 7</span></div><div className="grid grid-cols-2 gap-5 mt-6"><div><p className="text-xs text-muted-foreground mb-3">EXAMPLE VALUE</p><div className="grid gap-2">{memoryPairs.map(pair=><Button key={pair.name} variant="outline" className={`justify-start font-mono text-xs ${selected===pair.name?'memory-selected':''} ${matched.includes(pair.name)?'memory-matched':''}`} disabled={matched.includes(pair.name)} aria-pressed={selected===pair.name} onClick={()=>{setSelected(pair.name);setFeedback('');}}>{matched.includes(pair.name)?<Check size={14}/>:null}{pair.value}</Button>)}</div></div><div><p className="text-xs text-muted-foreground mb-3">DATA TYPE</p><div className="grid gap-2">{['Boolean','Object','String','Undefined','Number','Array','Null'].map(name=><Button key={name} variant="outline" disabled={matched.includes(name)||!selected} className={`justify-start ${matched.includes(name)?'memory-matched':''}`} onClick={()=>match(name)}>{matched.includes(name)?<Check/>:null}{name}</Button>)}</div></div></div>{feedback&&<p role="status" className="feedback">{feedback}</p>}{matched.length===7&&<div className="feedback text-center"><Sparkles className="mx-auto text-primary"/><strong>All connected! You know your types.</strong></div>}<Button variant="ghost" className="mt-4" onClick={()=>{setMatched([]);setSelected(null);setFeedback('');}}><RotateCcw/> Start over</Button></div>;}

export function Quiz({resetKey}:{resetKey:number}){return <QuizRound key={resetKey}/>;}
function QuizRound(){const [index,setIndex]=useState(0);const [score,setScore]=useState(0);const [answer,setAnswer]=useState<string|null>(null);const item=challenge[index];const reset=()=>{setIndex(0);setScore(0);setAnswer(null);};return <div className="activity max-w-3xl mx-auto">{item?<><div className="flex justify-between gap-4"><span className="eyebrow">QUESTION {index+1} OF 5</span><span className="text-sm text-muted-foreground">Score: {score} / 5</span></div><div className="progress-track mt-4"><progress aria-label="Quiz progress" value={index} max={5}/></div><div className="mystery">{item.expression}</div><h3 className="text-base mb-4">{index===0?'What is the type of x?':'What does this return?'}</h3><div className="grid grid-cols-2 gap-3">{item.options.map((option,i)=><Button key={option} variant="outline" className="justify-start h-12" disabled={!!answer} onClick={()=>{setAnswer(option);if(option===item.answer)setScore(s=>s+1);}}><span className="text-muted-foreground text-xs mr-2">{String.fromCharCode(65+i)}</span>{option}</Button>)}</div>{answer&&<><div role="status" className={`feedback ${answer===item.answer?'':'wrong'}`}><strong>{answer===item.answer?'Correct!':`The answer is ${item.answer}.`}</strong><p className="mt-1">{item.explanation}</p></div><div className="flex justify-end mt-4"><Button onClick={()=>{setIndex(i=>i+1);setAnswer(null);}}>{index===4?'Finish challenge':'Next question'}<ArrowRight/></Button></div></>}</>:<div className="text-center py-8"><Trophy size={52} className="text-primary mx-auto"/><p className="text-5xl font-bold my-6">{score} <span className="text-muted-foreground text-2xl">/ 5</span></p><h3 className="text-2xl font-semibold">{scoreMessage(score,5)}</h3><p className="text-muted-foreground text-sm mt-3 mb-6">{score*20}% correct · Every experiment makes you better.</p><Button onClick={reset}><RotateCcw/> Try again</Button></div>}</div>;}
