import { useEffect, useRef, useState } from 'react';
import { Play, RotateCcw, Terminal, Check, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { executeCode, type Execution } from '@/lib/playground';
const quick=['"Hello"','100','true','undefined','null','123n','Symbol("id")','{name: "Alex"}','[1, 2, 3]','function() {}'];
export function Playground({expression,onExpressionUsed}:{expression:string|null;onExpressionUsed:()=>void}) {
 const [code,setCode]=useState('let value = 100;');const [result,setResult]=useState<Execution>({value:'100',type:'number',detected:'Number',isArray:false});const [busy,setBusy]=useState(false);const request=useRef(0);
 async function run(source=code){const id=++request.current;setBusy(true);const output=await executeCode(source);if(id===request.current){setResult(output);setBusy(false);}}
 useEffect(()=>{if(expression){const source=`let value = ${expression};`;setCode(source);void run(source);onExpressionUsed();}},[expression]);
 useEffect(()=>{const timer=setTimeout(()=>{void run(code);},450);return()=>clearTimeout(timer);},[code]);
 return <><div className="code-window grid md:grid-cols-2"><div className="min-w-0"><div className="code-head"><span className="dot"/><span className="dot"/><span className="dot"/><span className="ml-3 font-mono">playground.js</span><span className="ml-auto text-xs">JavaScript</span></div><label htmlFor="code-editor" className="sr-only">JavaScript code editor</label><textarea id="code-editor" spellCheck={false} className="editor" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run();}}}/><div className="flex items-center justify-between px-5 pb-5"><Button size="sm" onClick={()=>void run()} disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Play/>} Run Code</Button><Button size="icon" variant="ghost" aria-label="Reset playground" title="Reset playground" onClick={()=>setCode('let value = 100;')}><RotateCcw/></Button></div></div><div className="min-w-0 border-t md:border-t-0 md:border-l border-border"><div className="code-head"><Terminal size={14}/><span className="ml-2">OUTPUT</span><span className="ml-auto flex items-center gap-1 text-success"><span className="h-1.5 w-1.5 rounded-full bg-success"/> Live</span></div><div className="output" aria-live="polite">{result.error?<div className="feedback wrong"><strong>Let's try that again.</strong><p className="mt-2">{result.error}</p></div>:<><div className="text-xs text-muted-foreground mb-2">VALUE</div><pre className="font-mono text-code text-lg whitespace-pre-wrap break-all">{result.value}</pre><div className="text-xs text-muted-foreground mt-6 mb-2">TYPEOF VALUE</div><div className="font-mono"><span className="text-muted-foreground">→ </span><span className="text-primary">"{result.type}"</span></div><div className="flex gap-2 items-center text-xs mt-6 text-muted-foreground"><Check size={14} className="text-success"/> Detected: <strong className="text-foreground">{result.detected}</strong></div>{result.isArray&&<p className="font-mono text-xs mt-3 text-code">Array.isArray(value) → true</p>}{result.detected==='Null'&&<p className="text-xs text-muted-foreground mt-3">Null is a primitive. The "object" result is a historical quirk.</p>}</>}</div></div></div><div className="mt-5 flex flex-wrap items-center gap-2"><span className="text-xs text-muted-foreground mr-2">QUICK EXPERIMENTS</span>{quick.map(value=><Button key={value} size="sm" variant="outline" className="font-mono text-xs" onClick={()=>{setCode(`let value = ${value};`);void run(`let value = ${value};`);}}>{value}</Button>)}</div></>;
}
